### ISSUE TITLE
Ceph MGR fails to load MGR modules after rebuild

### ISSUE THREAD

**Issue by p-na** [ricardoasmarques/ceph-dev-docker#34]
```
2018-10-31 13:52:33.781 7f978235e740 10 mgr[py] loaded 10 options
2018-10-31 13:52:33.781 7f978235e740  4 mgr[py] Standby mode not provided by module 'balancer'
2018-10-31 13:52:33.781 7f978235e740  1 mgr[py] Loading python module 'crash'
2018-10-31 13:52:33.801 7f978235e740 10 mgr[py] Computed sys.path '/ceph/src/pybind:/ceph/build/lib/cython_modules/lib.3::/usr/lib/python36.zip:/usr/lib64/python3.6:/usr/lib64/python3.6:/usr/lib64/python3.6/lib-dynload:/usr/lib64/python3.6/site-packages:/usr/lib/python3.6/site-packages:/usr/local/lib64/python3.6/site-packages:/usr/local/lib/python3.6/site-packages:/ceph/src/pybind/mgr'
2018-10-31 13:52:33.813 7f978235e740 -1 mgr[py] Module not found: 'mgr_module'
2018-10-31 13:52:33.813 7f978235e740 -1 mgr[py] Traceback (most recent call last):
  File "/ceph/src/pybind/mgr/mgr_module.py", line 8, in <module>
    import rados
ImportError: Interpreter change detected - this module can only be loaded into one interpreter per process.

2018-10-31 13:52:33.813 7f978235e740 -1 mgr[py] Class not found in module 'crash'
2018-10-31 13:52:33.813 7f978235e740 -1 mgr[py] Error loading module 'crash': (22) Invalid argument
2018-10-31 13:52:33.813 7f978235e740  1 mgr[py] Loading python module 'dashboard'
2018-10-31 13:52:33.837 7f978235e740 10 mgr[py] Computed sys.path '/ceph/src/pybind:/ceph/build/lib/cython_modules/lib.3::/usr/lib/python36.zip:/usr/lib64/python3.6:/usr/lib64/python3.6:/usr/lib64/python3.6/lib-dynload:/usr/lib64/python3.6/site-packages:/usr/lib/python3.6/site-packages:/usr/local/lib64/python3.6/site-packages:/usr/local/lib/python3.6/site-packages:/ceph/src/pybind/mgr'
2018-10-31 13:52:33.849 7f978235e740 -1 mgr[py] Module not found: 'mgr_module'
2018-10-31 13:52:33.849 7f978235e740 -1 mgr[py] Traceback (most recent call last):
  File "/ceph/src/pybind/mgr/mgr_module.py", line 8, in <module>
    import rados
ImportError: Interpreter change detected - this module can only be loaded into one interpreter per process.

2018-10-31 13:52:33.849 7f978235e740 -1 mgr[py] Class not found in module 'dashboard'
2018-10-31 13:52:33.849 7f978235e740 -1 mgr[py] Error loading module 'dashboard': (22) Invalid argument
2018-10-31 13:52:33.849 7f978235e740  1 mgr[py] Loading python module 'devicehealth'
2018-10-31 13:52:33.873 7f978235e740 10 mgr[py] Computed sys.path '/ceph/src/pybind:/ceph/build/lib/cython_modules/lib.3::/usr/lib/python36.zip:/usr/lib64/python3.6:/usr/lib64/python3.6:/usr/lib64/python3.6/lib-dynload:/usr/lib64/python3.6/site-packages:/usr/lib/python3.6/site-packages:/usr/local/lib64/python3.6/site-packages:/usr/local/lib/python3.6/site-packages:/ceph/src/pybind/mgr'
2018-10-31 13:52:33.889 7f978235e740 -1 mgr[py] Module not found: 'mgr_module'
2018-10-31 13:52:33.889 7f978235e740 -1 mgr[py] Traceback (most recent call last):
  File "/ceph/src/pybind/mgr/mgr_module.py", line 8, in <module>
    import rados
ImportError: Interpreter change detected - this module can only be loaded into one interpreter per process.

2018-10-31 13:52:33.889 7f978235e740 -1 mgr[py] Class not found in module 'devicehealth'
2018-10-31 13:52:33.889 7f978235e740 -1 mgr[py] Error loading module 'devicehealth': (22) Invalid argument
2018-10-31 13:52:33.889 7f978235e740  1 mgr[py] Loading python module 'diskprediction'
2018-10-31 13:52:33.913 7f978235e740 10 mgr[py] Computed sys.path '/ceph/src/pybind:/ceph/build/lib/cython_modules/lib.3::/usr/lib/python36.zip:/usr/lib64/python3.6:/usr/lib64/python3.6:/usr/lib64/python3.6/lib-dynload:/usr/lib64/python3.6/site-packages:/usr/lib/python3.6/site-packages:/usr/local/lib64/python3.6/site-packages:/usr/local/lib/python3.6/site-packages:/ceph/src/pybind/mgr'
2018-10-31 13:52:33.929 7f978235e740 -1 mgr[py] Module not found: 'mgr_module'
2018-10-31 13:52:33.929 7f978235e740 -1 mgr[py] Traceback (most recent call last):
  File "/ceph/src/pybind/mgr/mgr_module.py", line 8, in <module>
    import rados
ImportError: Interpreter change detected - this module can only be loaded into one interpreter per process.

2018-10-31 13:52:33.929 7f978235e740 -1 mgr[py] Class not found in module 'diskprediction'
2018-10-31 13:52:33.929 7f978235e740 -1 mgr[py] Error loading module 'diskprediction': (22) Invalid argument
2018-10-31 13:52:33.929 7f978235e740  1 mgr[py] Loading python module 'hello'
2018-10-31 13:52:33.953 7f978235e740 10 mgr[py] Computed sys.path '/ceph/src/pybind:/ceph/build/lib/cython_modules/lib.3::/usr/lib/python36.zip:/usr/lib64/python3.6:/usr/lib64/python3.6:/usr/lib64/python3.6/lib-dynload:/usr/lib64/python3.6/site-packages:/usr/lib/python3.6/site-packages:/usr/local/lib64/python3.6/site-packages:/usr/local/lib/python3.6/site-packages:/ceph/src/pybind/mgr'
2018-10-31 13:52:33.961 7f978235e740 -1 mgr[py] Module not found: 'mgr_module'
2018-10-31 13:52:33.961 7f978235e740 -1 mgr[py] Traceback (most recent call last):
  File "/ceph/src/pybind/mgr/mgr_module.py", line 8, in <module>
    import rados
ImportError: Interpreter change detected - this module can only be loaded into one interpreter per process.
```
Current build flags in this project:
`-DWITH_PYTHON3=ON -DWITH_PYTHON2=OFF -DMGR_PYTHON_VERSION=3 -DWITH_TESTS=ON -DWITH_CCACHE=ON`

**Another combination which does not trigger the issue:**
`-D WITH_PYTHON3=ON -D WITH_TESTS=ON -D WITH_CCACHE=ON -D ENABLE_GIT_VERSION=OFF WITH_MGR_DASHBOARD_FRONTEND=OFF`

Likely relevant (bad):
`-D WITH_PYTHON2=OFF` and `-D MGR_PYTHON_VERSION=3`

This looks like something in master has changed and prevents us from using a Python3 only Ceph, but as I'm not sure about that, I opened the issue here first.

**Workaround**:

Use the build flags known to work and adapt the `setup-ceph.sh` file inside or outside of your container. Adapting it outside requires you to build a new image and create a new container out of that image.

**Comment by votdev** [comment]
The workaround works for me.

**Comment by s0nea** [comment]
Here is the output of the vstart command as well:

```ceph-dev /ceph/build # RGW=1 ../src/vstart.sh -n -x
=== mgr.x ===
Stopping Ceph mgr.x on ceph-dev...kill  4755...done
=== mon.c ===
Stopping Ceph mon.c on ceph-dev...kill  4589...done
=== mon.b ===
Stopping Ceph mon.b on ceph-dev...kill  4548...done
=== mon.a ===
Stopping Ceph mon.a on ceph-dev...kill  4507...done
rm -f core*
hostname ceph-dev
ip 192.168.2.101
port 8080
/ceph/build/bin/ceph-authtool --create-keyring --gen-key --name=mon. /ceph/build/keyring --cap mon 'allow *'
creating /ceph/build/keyring
/ceph/build/bin/ceph-authtool --gen-key --name=client.admin --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow *' --cap mgr 'allow *' /ceph/build/keyring
/ceph/build/bin/ceph-authtool --gen-key --name=client.fs --cap mon 'allow r' --cap osd 'allow rw tag cephfs data=*' --cap mds 'allow rwp' /ceph/build/keyring
/ceph/build/bin/ceph-authtool --gen-key --name=client.rgw --cap mon 'allow rw' --cap osd 'allow rwx' --cap mgr 'allow rw' /ceph/build/keyring
/ceph/build/bin/monmaptool --create --clobber --add a 192.168.2.101:8080 --add b 192.168.2.101:8081 --add c 192.168.2.101:8082 --print /tmp/ceph_monmap.4843
/ceph/build/bin/monmaptool: monmap file /tmp/ceph_monmap.4843
/ceph/build/bin/monmaptool: generated fsid 014daccf-8197-4273-8a40-9e435c0a1f5e
epoch 0
fsid 014daccf-8197-4273-8a40-9e435c0a1f5e
last_changed 2018-10-30 14:36:03.680166
created 2018-10-30 14:36:03.680166
0: 192.168.2.101:8080/0 mon.a
1: 192.168.2.101:8081/0 mon.b
2: 192.168.2.101:8082/0 mon.c
/ceph/build/bin/monmaptool: writing epoch 0 to /tmp/ceph_monmap.4843 (3 monitors)
rm -rf -- /ceph/build/dev/mon.a
mkdir -p /ceph/build/dev/mon.a
/ceph/build/bin/ceph-mon --mkfs -c /ceph/build/ceph.conf -i a --monmap=/tmp/ceph_monmap.4843 --keyring=/ceph/build/keyring
rm -rf -- /ceph/build/dev/mon.b
mkdir -p /ceph/build/dev/mon.b
/ceph/build/bin/ceph-mon --mkfs -c /ceph/build/ceph.conf -i b --monmap=/tmp/ceph_monmap.4843 --keyring=/ceph/build/keyring
rm -rf -- /ceph/build/dev/mon.c
mkdir -p /ceph/build/dev/mon.c
/ceph/build/bin/ceph-mon --mkfs -c /ceph/build/ceph.conf -i c --monmap=/tmp/ceph_monmap.4843 --keyring=/ceph/build/keyring
rm -- /tmp/ceph_monmap.4843
/ceph/build/bin/ceph-mon -i a -c /ceph/build/ceph.conf
/ceph/build/bin/ceph-mon -i b -c /ceph/build/ceph.conf
/ceph/build/bin/ceph-mon -i c -c /ceph/build/ceph.conf
Populating config ...
creating /ceph/build/dev/mgr.x/keyring
/ceph/build/bin/ceph -c /ceph/build/ceph.conf -k /ceph/build/keyring -i /ceph/build/dev/mgr.x/keyring auth add mgr.x mon 'allow profile mgr' mds 'allow *' osd 'allow *'
added key for mgr.x
/ceph/build/bin/ceph -c /ceph/build/ceph.conf -k /ceph/build/keyring config set mgr mgr/dashboard/x/server_port 9080
/ceph/build/bin/ceph -c /ceph/build/ceph.conf -k /ceph/build/keyring config set mgr mgr/restful/x/server_port 10080
Starting mgr.x
/ceph/build/bin/ceph-mgr -i x -c /ceph/build/ceph.conf
/ceph/build/bin/ceph -c /ceph/build/ceph.conf -k /ceph/build/keyring tell mgr dashboard ac-user-create admin admin administrator
2018-10-30 14:36:15.995 7f81a7004700  0 mgrc start_command no mgr session (no running mgr daemon?), waiting
no valid command found; 10 closest matches:
balancer status
balancer mode none|crush-compat|upmap
balancer on
balancer off
balancer eval {<option>}
balancer eval-verbose {<option>}
balancer optimize <plan> {<pools> [<pools>...]}
balancer show <plan>
balancer rm <plan>
balancer reset
Error EINVAL: invalid command```

The workaround solves the issue for me too, thank you :)
