### ISSUE TITLE
`npm install` fails due to permission problems

### ISSUE THREAD

**Issue by p-se** [ricardoasmarques/ceph-dev-docker#67]
Please note that this issue has originally been reported in oftc#ceph-dashboard by using `ceph-dev-docker`. I just happened to be able reproduce it on my **customized** fork using `sudo`. As `ceph-dev-docker` runs as root by default, it is not necessary to use `sudo` to reproduce the problem here!

My proposed solution (as I do not have this problem with my fork) is to switch from root to some non-root user inside the container. Ceph doesn't require root anyway and it will prevent mixed owners in the ceph repo.

The workaround, which fixed the problem for `ceph-dev-docker` users is to install the frontend dependencies by calling `npm install --unsafe-perm` in `/ceph/src/pybind/mgr/dashboard/frontend`.

```
user@ceph-4 /ceph/src/pybind/mgr/dashboard/frontend (master*) $ sudo npm install   
Unhandled rejection Error: Command failed: /usr/bin/git submodule update -q --init --recursivec/pybind/mgr/dashboard/frontend/node_modules/.staging/typescript-7d3fd7c7 (11733ms)
fatal: failed to stat '/root/.npm/_cacache/tmp/git-clone-44f5e7c8': Permission denied

    at ChildProcess.exithandler (child_process.js:281:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)


> node-sass@4.11.0 install /ceph/src/pybind/mgr/dashboard/frontend/node_modules/node-sass
> node scripts/install.js

Unable to save binary /ceph/src/pybind/mgr/dashboard/frontend/node_modules/node-sass/vendor/linux-x64-57 : { Error: EACCES: permission denied, mkdir '/ceph/src/pybind/mgr/dashboard/frontend/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/ceph/src/pybind/mgr/dashboard/frontend/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/ceph/src/pybind/mgr/dashboard/frontend/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/ceph/src/pybind/mgr/dashboard/frontend/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/ceph/src/pybind/mgr/dashboard/frontend/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/ceph/src/pybind/mgr/dashboard/frontend/node_modules/node-sass/vendor' }

> node-sass@4.11.0 postinstall /ceph/src/pybind/mgr/dashboard/frontend/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node8 /ceph/src/pybind/mgr/dashboard/frontend/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node8',
gyp verb cli   '/ceph/src/pybind/mgr/dashboard/frontend/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@8.15.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.16
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 8.15.1
gyp verb command install [ '8.15.1' ]
gyp verb install input version string "8.15.1"
gyp verb install installing version: 8.15.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.15.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/ceph/src/pybind/mgr/dashboard/frontend/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '8.15.1' ]
gyp verb install input version string "8.15.1"
gyp verb install installing version: 8.15.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.15.1
gyp verb ensuring nodedir is created /ceph/src/pybind/mgr/dashboard/frontend/node_modules/node-sass/.node-gyp/8.15.1
gyp WARN install got an error, rolling back install
gyp verb command remove [ '8.15.1' ]
gyp verb remove using node-gyp dir: /ceph/src/pybind/mgr/dashboard/frontend/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 8.15.1
gyp verb remove removing development files for version: 8.15.1
gyp WARN install got an error, rolling back install
gyp verb command remove [ '8.15.1' ]
gyp verb remove using node-gyp dir: /ceph/src/pybind/mgr/dashboard/frontend/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 8.15.1
gyp verb remove removing development files for version: 8.15.1
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/ceph/src/pybind/mgr/dashboard/frontend/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.15.0-47-generic
gyp ERR! command "/usr/bin/node8" "/ceph/src/pybind/mgr/dashboard/frontend/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /ceph/src/pybind/mgr/dashboard/frontend/node_modules/node-sass
gyp ERR! node -v v8.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1

```

**Comment by p-se** [comment]
Haven't been an issue for a while so I'm going to close this.
